config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "grams#index"
  resources :grams do
    resources :comments, only: :create
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :gram
  belongs_to :user
end

app/models/gram.rb
class Gram < ActiveRecord::Base
  validates :message, presence: true
  validates :picture, presence: true
  has_many :comments


  mount_uploader :picture, PictureUploader
  
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :grams
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  def render_not_found(status=:not_found)
    render text: "#{status.to_s.titleize} :(", status: status
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @gram = Gram.find_by_id(params[:gram_id])
    return render_not_found if @gram.blank?

    @gram.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
  end

  private


  def comment_params
    params.require(:comment).permit(:message)
  end

end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @grams = Gram.all
  end

  def new
    @gram = Gram.new
  end

  def create
    @gram = current_user.grams.create(gram_params)

    if @gram.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end

  def edit
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
  end

  def update
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user

    @gram.update_attributes(gram_params)
    if @gram.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
    @gram.destroy
    redirect_to root_path
  end


  private

  def gram_params
    params.require(:gram).permit(:message, :picture)
  end


  def render_not_found(status=:not_found)
    render text: "#{status.to_s.titleize} :(", status: status
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<div class="card-panel col s6 center card form">
  <h2>Update Your Post</h2>

  <%= simple_form_for @gram do |f| %>
    <%= f.input :message %>
    <%= f.input :picture %>
    <%= f.submit 'Update', class: 'my-btn' %>
  <% end %>
  
</div>

app/views/grams/index.html.erb
<% @grams.each do |gram| %>
  <div class="container grey col s12">
    <div class="col s12">
      <div class="card-panel z-depth-5">
        <div class="blue-text">
          <h4>
            <%= gram.user.email.split("@")[0] %>
            <span class="grey-text text-lighten-2 small thin">
              <%="#{time_ago_in_words(gram.created_at)} ago"%>
            </span>
          </h4>
        </div>
        <%= image_tag gram.picture, class: 'responsive-img' %>
        <h5> 
          <%= gram.message %>
        </h5>
        <br class="clear-fix" />
        
        <div class="card-panel grey lighten-4">
            <h5>Comments</h5>
            <% gram.comments.each do |comment| %>
            <div class="comments">
              <div class="comment">
                <p class="left">
                  <span class="comment_handle">
                    <%= comment.user.email.split("@")[0] %>: 
                  </span>
                  <%= comment.message %> <br class="clear-fix" />
                </p>
              </div>
            </div>
          <% end %>
          <br class="clear-fix" />
          <br class="clear-fix" />

          <%= simple_form_for Comment.new, url: gram_comments_path(gram) do |f| %>
            <%= f.input :message %>
            <%= f.submit 'Add Comment', class: 'my-btn' %>
          <% end %>

        <div class="gram-actions">
          <% if current_user && current_user == gram.user %>
            <%= link_to 'Edit', edit_gram_path(gram)%>
            <%= link_to 'Delete', gram_path(gram), method: :delete, data: {confirm: 'Are you sure?'} %>      
          <% end %>
        </div>
          </div>
      </div>
    </div>
  </div>
<% end %>

app/views/grams/new.html.erb
<div class="container col s12">	
	<div class="card-panel col s8 center card form">
	  
	  <h1>New Post</h1>
	  <div class="card_panel col s4 grey lighten-4">
	  <div class="center">
		  <%= simple_form_for @gram do |f| %>
		    
		    <div class="container col s2 small center form-input">
		    	<%= f.input :picture%>
		    	<%= f.input :message%>
		    	<%= f.submit "Upload", class: 'my-btn center form-action' %>
		    </div>
		  <% end %>
		 </div>
	  </div>
	</div>
</div>

app/views/grams/show.html.erb
<%= @gram.inspect %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
  <html>
  <head>
    <title>Imstagran</title>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Josefin+Sans:400,100,300,600,700' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1.0"/>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body class="grey">
    <div class="add brand">
    <a href="/#" class="white-text">
        Imstagran
    </a>
    </div>
    <div class="container top-nav grey">
      <div class="col s12">
      
        <br class="clear-fix" />
        <div class="container">
          <% if current_user %>
            <!-- nav links -->
            <div class="add col s4 push-s6 right">
              <%= link_to "New Post", new_gram_path %>
              <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
              <a href="#">^Top</a>
            </div>
          <% else %>
            <div class="add center">
              <%= link_to "Sign In", new_user_session_path %>
              <%= link_to "Sign Up", new_user_registration_path %>
              <a href="#">^Top</a>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <br class="clear-fix" />
    <br class="clear-fix" />
    <%= yield %>
  </body>
</html>